// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD9YI85czzY5g_9c_jt583AIu2gmY3Kt8',
    appId: '1:434519431859:web:b80f5d936e726b5c4baec6',
    messagingSenderId: '434519431859',
    projectId: 'banco-de-usuarios-alunos',
    authDomain: 'banco-de-usuarios-alunos.firebaseapp.com',
    storageBucket: 'banco-de-usuarios-alunos.firebasestorage.app',
    measurementId: 'G-9374VX93FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5wp-RKG9Uwmytv85ZmWMFE8QRNhKqwjc',
    appId: '1:434519431859:android:7e916de4094fd0bf4baec6',
    messagingSenderId: '434519431859',
    projectId: 'banco-de-usuarios-alunos',
    storageBucket: 'banco-de-usuarios-alunos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAns3edpDBkOe7PWkjdQYr0VvigeID60ME',
    appId: '1:434519431859:ios:762b46957a8351e04baec6',
    messagingSenderId: '434519431859',
    projectId: 'banco-de-usuarios-alunos',
    storageBucket: 'banco-de-usuarios-alunos.firebasestorage.app',
    iosBundleId: 'com.example.portalDoAluno',
  );

}